# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'
      demands:
      - npm

    variables:
      wwwrootDir: 'Candyshop/wwwroot'
      dotnetSdkVersion: '6.x'

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'

    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: $(wwwrootDir)

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop
data:image/pjpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCABAAEADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD+9VUYHkY4PX25pwjYfOPmDY4yoxuIx95gCSxCgDJLMMDGSL6xEnBXPB6hf6IvWvyG/wCCy37a2v8A7Gv7Ln23wLef2X8QfifrFz4O8Pa1DJD9s8P6fFaSTa/q+nI52nUo7W5tLGxd45UtJr6Odk3xo6ZV8RDDUZ1Kl1FK9/NbL1ZvhqE8ViKWGp/xK0uWGjavpv2Plj/gp3/wXA+Hn7LD+KPhP8D5LLxx8VtIGraD4h1mWC6/sXwRq39lxTjUtNku9Pn0rxYdKluYbTU7e2b7CbqHUtLj1F9WsprJP4lPj7/wUi/bW+P3j4eMPGXxj+IGvabbXt/f6N4RuEv59Atp9RnlvFtdM0yRLi80e1sLLyLDyrZ7BIo/tUN04hU2Z/Vn4HfsQaV8frMfFT4nXWt6naeMHjubXQpHe2kaBFOZr2+Zrm5ugZpLqTcJ/NvTMbqW4SVpo5v0g8C/8E5/2c9H082b/CXw9ew3KOs0+o/2heTSEqisBNc6hM4Z8uCxBA38IQdtfBVs5qVartScoptKErOyukr+iTV9N77n7LlXh+o4OjUrV3Tq1YKUl8WvLFzWn956dloz+bj4Lf8ABUr9ub4DxWeh/D/47eLPDmgQXt7e3vhDSY/Fj+ENNfWHt5bt4dJvJJNAbV5ZI32iy8L6hdSzM5eEReVPJ/W1/wAEz/8Agut4Q/aK1Twb8Hv2k30nwP8AETXdOnsdK+Ikn2bRvCnibxHbguljfiU2sPh+81G2W7tdL4tzqd5ZS2402wupZFn+Ovij/wAEx/gB4m06xsNJ8FWOi6fpBuLtrLSfMtb/AFG8lHl26XerKr3sen2iGUpa2bW/nSPHJdPceREo/H34tf8ABOn4i/s92erePPD0rXfhiw/tO4m0jSpr17jSrYprE2nHT9RWGwv7iHTr69065ZEWwkSS2LQ3awvJbz3hM89lWUZQlRk5KMVb3dUr2+Xnu+uxyZx4f4mNGVak416abS5X7/uqLu47/wCS10tr/pGJNNESzhnyy7o5X+bgIxPlkl0Kh4ydwQgOuA2c10tpML5CdvzD5WUkD5uhAzyBngEfXvX4S/8ABCL9ufxH+2V+yxceHvibqcmr/Fj4G6hYeFte1m7Fomo+IvDOox3X/CKavfW9uFk+1xW2nSaff3d0DNfXVo92x3u2f3KjYwOrRgKQwz8q845OQRg5x7HPINfc0K0MRSjVg7xkvxW+3mfkmIo1MPWqUasXGdOTi099NvwsdvX8rf8Awcg+H73xRrH7IWjRSwtaf2j8R7qa2kV2eTF54GDthy8LALBGqqiLMVSQNmJ2B/qkr+Y//gur4a8Q+Kf2gf2MY9I0qK70621K/wDD2t3pCPLFL418X6Bb6RbPG2XSCOPQ9Vv2lRHRlheN3jARW83PE3gJpdZR/Nfke1wxTnVznDKMXPkjVqyilf3acby3027/AHo5H4CeGBoHwy+HtlJbG2kh8OacjRzQeWDGYUeMqmIY9vlyB1EYTbGVJGAAfquwhhkhVotrInH7sFeo6gs5GCAcPG4GcbXDYr4O/aC0+8szolwPHPxL8MaAkH2Sx8PfCzQo7rVdS1SBbma3utU1YaXef2Vp4jhjtYv7RudM0m03me+v7ZcOngf7LHiu51LWdP8AGuleKP2pJ7LUpJ47fSPjreyWr2UULHSXZ/DX9m2baeLi7/06083ZeTW8T6hbQ3enobg/DJwpNOcU9VF2Sd22rvW17217n9G4GPP7HDyreyqunGVO6b9xRi3FaaKV7n6xahAIxcMFeJDGqsrI0bL99i5aRm4AHOXJVQrOqq6M/i3jXw/ZeJ/Dus6Fe28M9lf6fPDOJkLrLC42sqEoysxAO0Z3M6rGAWcKfmb9qzxfqesxQaGni/4jeFWtLW41aTXvh7evHc6fDp1lqF/NLOfst1Lc7razvmtLO3s7ie6u4hYhGnu7ONvDf2U/Ft14o8VW2peFf2ifiJ8VPCE1jI+qaD8YPBV9oOravps0ckdtqug6jeeHfCWqi8sNVt7eKdrrTZ9OmsJLiEsdq3bTiXCs5ezSSi+RcyUbSSW1r28tn5HRWcqEuRS9pNwc7crvJJKMuZae9y39V2PTv+DfDRNV8A/tiftX+C7a3ntvDt58Pf7W8sW7BHn0rxvo9rYvM/k7hPbW+pazEi4PyzyCNCNrJ/Xm0RAPysxGeQCWz0ztAyD6jAx0IFfzu/8ABJ7QU8M/t2ftcaa2iSWtpceDNGOi615iCK8tbjxJpmv3FhFCZ/NeSOw1vS3nmhhaCJgscsqvLEsn9HIjyoX5cgAZOCCRgEZYc5Prz3r7rh5uWWpt83s24PW/vO2qfXve/wDkv5v4voSpZ1WXK6ftFCsk1yvkaTs0vLpt0Nqvyw/b78F29/4v+GfiaewS9tkluJJ5ZJFV7XUPC7Xl1os9sjqWM0M2u3+RGyAx+VxuTcf1Pr5K/bF8DR+JfhRfeIY5Zo9S8FTR6vaJChdZ7e4uLaz1COdASzRx2r/atyFGX7M2WCt8vdjqCxGGqQe/K5Jea1/Az4Wx6y3O8HiH8M5Sw8k1e8a69m09G7NtJ/fdbn45jw3Z6iryzTTQB3aMXEdyzSO4JIjBcKrs7chWWaNNroykDjxnx5eeHtMuorePU7Wwnjnji1HxBrN4qRW7XM/2WytrNbrzJbi9uXkmEMVsQYYoJJCcbAPSGOtahpck1j5kNyypJFBM7NNHEpVXMauHIuIIAVCtuLSAKR/DXzT4y8S+INN1yOzHww1TUWtfNSx1U6j4WuIpVciOeRPtGrWkyvJuI8m5Rp2BMIiGcV+cSlGVSdJxvKlL3nrurWd9nff7+7P694bw2ExrhanavSUIRvy2uoxs4u67X1dkmrmppF54f1LxhZ2h1nTfENrdXx0hNUsLlbifT7+Cwu9XuLW7tmW3mSG+06x81TMrRCVYS8bExsfoM+GNK00xywWu4/PIrZXcgkGDGhVFxGqkrHkGQJ8jSMgUL8V6L4l8QHxBbXD/AAn1qK/e5jgS40/UPCsJtYmlCN5kcetTxwbIZGN7IFZ5RKgRSykD6+ll1aC0tJrxfKuZLRJjAjNMoEykQq20NG0gi4kETMBleTxWdSdOP7p03L2srtxdpRatK6u0tUn/AMOd2d4OhhaqlU9nGpZwl8LklZaNx5rWXvP5bvQ+0v8Agnd4S8Tx/tF/HDxjcWunx+Dbn4ZfDHT9IngkY6n/AMJBLfayPEK3QQj5Wg0PQwROqH90ogj+zkhf2YCBcDGdpPXk5PXJ/rX50f8ABPuws47HxvrNprVjq1zqtr4d03W9Lsb6zeXwdd+H1vptOstZ05LqS7tL3xLp+vtrGnpLbQhNJs7edmltr/Tbi5/SGv0HJKCw2X0qcXLlm5VPe3ak7rvsttdNj+QON8xhmXEeNrU0lToqnhIcqsmsPTjTk1ovikm/MK5TxtpVp4g8JeI9Cvgv2PVtG1PTrppNojiiurKeJpZCzDakRYOWAYoBv2hVZl6onAJPQV+PH/BXv9tLwN8A/wBlvxx4N0XxP4b1X4ofFG+Hwp0vwvBqFpqt9pY1i2ludfu9e0ezuTeWtpB4djuxdWt79k+02txIV/clpB7FOhUxU40aUPaTq3hFXsm2tFdd/L8j4+eKp4NfWakuRUHGrdbrlnGz+/Zuy03Phy11ddN1C/sZcedazShdzxbXdHPmSJGu4ZncM+7zQfL8sMisWVYxa2Otxyjy7dsziGV2fYohTZIMtiQcIyNtdRnayjcSob5K8O/ESTxZoul61NFJp+v/ANn6TcazpbeVjzdQ0y1v7PVbX7PLPENN1azu7e+tVjvb2GxnmfRriZtWsLsR1Lzx3rNlKUsdRa1bzCHgH2eSORWeFwxR2Eh3shTOCV3YSvy3FUnhsdj6UlyVKddxlF9LSavrrZ23+fU/qTIM3qrB4LHYWs+SvRg1ODWq5Icut2k1G199fM+priwsdIdoVWJQnzb4WiIlJPv5PyLgFyRld2W6rSXetxSunmy7lC28X7pzNInOyKNUjUlmeXy1C/KobD7v3YB+OJviN4muLnFxfzsEf5fKgAXeeBvbypAwAwAu4YxuABOToaj8Tz8O/C3iDx1rd1ifQtNvtUsIWCzNJeWcEk0AMTIA/muFREYtGsrRs8ciBtvLTlGeIoybTXOkn0tL3Xt1s2l59LnTmuPxFWjiajrSnOVKrKDm+Z3cL9dLrZfgf16fB3wlH4H+GngrwysQjm0vw9p8V5tUAPqE8EdzqMrEAbmkvJpTuPJA6L0r02vwy/4IN/tu/EP9r39kvSIPjb45ufHfxg8Fafpp1fxBq2l22ka3rOj3M1/orPqIt7PToNXv9D8R+H9c0rVNRtbKOS2Z7C11qS51KUX9/wDubX6tShyUqUUrJUqdl5OKf9d9z+Wa03Ur15yfNN1qjm+8+Z8x/9k=
- stage: 'Deploy'
  displayName: 'Deploy the web application'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: dev
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'Resource Manager - Stjarnorna - Candyshop'
              appName: '$(WebAppName)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
